### ISSUE TITLE
Docker image unavailable

### ISSUE THREAD

**Issue by sajmmon** [blawlor/field-of-genes#1]
Hi,
I try to run: docker run -it --rm blawlor/gccontent-experiment 2 4 
from /field-of-genes/gccontent-lib

And I get:
Unable to find image 'blawlor/gccontent-experiment:latest' locally
docker: Error response from daemon: pull access denied for blawlor/gccontent-experiment, repository does not exist or may require 'docker login'.
See 'docker run --help'.

**Comment by blawlor** [comment]
Hi sajammon,
   Thanks for bringing this to my attention. I have either misnamed the docker image in the documentation, or neglected to publish the image. I will investigate and get back.
Note that I intend to re-write a lot of the 'fabric' section to make use of the fact that since I wrote the original version, Swarm has been integrated into the Docker engine itself, so there will be some opportunity to simplify the deployment (no direct need to set up consul, for example).

**Comment by blawlor** [comment]
Hi sajammon,
   The problem appears to have been a mistake in the README documentation. I've updated this on branch bugfix/1 and tested. I will create a PR for this branch and if you find the updated doc (on the bugfix/1 branch) to have solved the problem, please let me know and I will merge the PR. Thanks for the catch.
